apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::905418111046:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-Jec1TjtBrQTh
      username: system:node:{{EC2PrivateDNSName}}    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-11T17:26:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1201"
  uid: 6be2c601-6864-401d-a22a-82f8394af805